export interface Currency {
  code: string;
  name: string;
  symbol: string;
  symbolPosition: "prefix" | "suffix";
}

export const currencies: Currency[] = [
  { code: "USD", name: "United States Dollar", symbol: "$", symbolPosition: "prefix" },
  { code: "EUR", name: "Euro", symbol: "€", symbolPosition: "prefix" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", symbolPosition: "prefix" },
  { code: "GBP", name: "British Pound", symbol: "£", symbolPosition: "prefix" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", symbolPosition: "prefix" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", symbolPosition: "prefix" },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr", symbolPosition: "prefix" },
  { code: "CNY", name: "China Yuan Renminbi", symbol: "¥", symbolPosition: "prefix" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", symbolPosition: "suffix" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", symbolPosition: "prefix" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", symbolPosition: "prefix" },
  { code: "AFN", name: "Afghanistan Afghani", symbol: "؋", symbolPosition: "prefix" },
  { code: "ALL", name: "Albanian Lek", symbol: "L", symbolPosition: "suffix" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", symbolPosition: "suffix" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", symbolPosition: "suffix" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", symbolPosition: "prefix" },
  { code: "AWG", name: "Aruban Guilder", symbol: "ƒ", symbolPosition: "prefix" },
  { code: "AZN", name: "Azerbaijan Manat", symbol: "₼", symbolPosition: "prefix" },
  { code: "BAM", name: "Bosnian Convertible", symbol: "KM", symbolPosition: "suffix" },
  { code: "BBD", name: "Barbados Dollar", symbol: "Bds$", symbolPosition: "prefix" },
  { code: "BDT", name: "Bangladesh Taka", symbol: "৳", symbolPosition: "prefix" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", symbolPosition: "suffix" },
  { code: "BHD", name: "Bahrain Dinar", symbol: "BD", symbolPosition: "prefix" },
  { code: "BIF", name: "Burundi Franc", symbol: "Fr", symbolPosition: "prefix" },
  { code: "BMD", name: "Bermudian Dollar", symbol: "BD$", symbolPosition: "prefix" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", symbolPosition: "prefix" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", symbolPosition: "prefix" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", symbolPosition: "prefix" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$", symbolPosition: "prefix" },
  { code: "BTN", name: "Bhutan Ngultrum", symbol: "Nu", symbolPosition: "prefix" },
  { code: "BWP", name: "Botswana Pula", symbol: "P", symbolPosition: "prefix" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", symbolPosition: "suffix" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", symbolPosition: "prefix" },
  { code: "CDF", name: "Congolais Franc", symbol: "Fr", symbolPosition: "prefix" },
  { code: "CLP", name: "Chile Peso", symbol: "$", symbolPosition: "prefix" },
  { code: "COP", name: "Colombian Peso", symbol: "$", symbolPosition: "prefix" },
  { code: "CRC", name: "Costa Rican Colon", symbol: "₡", symbolPosition: "prefix" },
  { code: "CVE", name: "Cape Verde Escudo", symbol: "$", symbolPosition: "suffix" },
  { code: "CYP", name: "Cyprus Pound", symbol: "£", symbolPosition: "prefix" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", symbolPosition: "suffix" },
  { code: "DJF", name: "Djibouti Franc", symbol: "Fr", symbolPosition: "prefix" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", symbolPosition: "suffix" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", symbolPosition: "prefix" },
  { code: "DZD", name: "Algerian Dinar", symbol: "دج", symbolPosition: "suffix" },
  { code: "EEK", name: "Estonian Kroon", symbol: "kr", symbolPosition: "suffix" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", symbolPosition: "prefix" },
  { code: "ERN", name: "Eritrean Nafka", symbol: "Nfk", symbolPosition: "prefix" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", symbolPosition: "prefix" },
  { code: "FJD", name: "Fiji Dollar", symbol: "FJ$", symbolPosition: "prefix" },
  { code: "FKP", name: "Falkland Is. Pound", symbol: "£", symbolPosition: "prefix" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", symbolPosition: "suffix" },
  { code: "GHS", name: "Ghana Cedi", symbol: "₵", symbolPosition: "prefix" },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£", symbolPosition: "prefix" },
  { code: "GMD", name: "Gambia Dalasi", symbol: "D", symbolPosition: "prefix" },
  { code: "GNF", name: "Guinea Franc", symbol: "Fr", symbolPosition: "prefix" },
  { code: "GQE", name: "Eqguinea Ekwele", symbol: "Ek", symbolPosition: "prefix" },
  { code: "GTQ", name: "Guatemala Quetzal", symbol: "Q", symbolPosition: "prefix" },
  { code: "GWP", name: "GuineaBissau Peso", symbol: "Fr", symbolPosition: "prefix" },
  { code: "GYD", name: "Guyana Dollar", symbol: "GY$", symbolPosition: "prefix" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", symbolPosition: "prefix" },
  { code: "HNL", name: "Hondura Lempira", symbol: "L", symbolPosition: "prefix" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", symbolPosition: "suffix" },
  { code: "HTG", name: "Haiti Gourde", symbol: "G", symbolPosition: "prefix" },
  { code: "HUF", name: "Hungary Forint", symbol: "Ft", symbolPosition: "suffix" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", symbolPosition: "prefix" },
  { code: "ILS", name: "New Israeli Shekel", symbol: "₪", symbolPosition: "prefix" },
  { code: "INR", name: "Indian Rupee", symbol: "₹", symbolPosition: "prefix" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", symbolPosition: "prefix" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", symbolPosition: "suffix" },
  { code: "ISK", name: "Iceland Krona", symbol: "kr", symbolPosition: "suffix" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", symbolPosition: "prefix" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "JD", symbolPosition: "prefix" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", symbolPosition: "prefix" },
  { code: "KGS", name: "Kyrgyzstan Som", symbol: "с", symbolPosition: "suffix" },
  { code: "KHR", name: "Cambodia Riel", symbol: "៛", symbolPosition: "suffix" },
  { code: "KMF", name: "Comoro Franc", symbol: "Fr", symbolPosition: "prefix" },
  { code: "KRW", name: "South Korea Won", symbol: "₩", symbolPosition: "prefix" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "KD", symbolPosition: "prefix" },
  { code: "KYD", name: "Cayman Is. Dollar", symbol: "CI$", symbolPosition: "prefix" },
  { code: "KZT", name: "Kazakhstan Tenge", symbol: "₸", symbolPosition: "prefix" },
  { code: "LAK", name: "Laotian Kip", symbol: "₭", symbolPosition: "suffix" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", symbolPosition: "prefix" },
  { code: "LKR", name: "Sri Lanka Rupee", symbol: "Rs", symbolPosition: "prefix" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", symbolPosition: "prefix" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", symbolPosition: "prefix" },
  { code: "LTL", name: "Lithuanian Litas", symbol: "Lt", symbolPosition: "suffix" },
  { code: "LVL", name: "Latvian Lats", symbol: "Ls", symbolPosition: "prefix" },
  { code: "LYD", name: "Libyan Dinar", symbol: "LD", symbolPosition: "prefix" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "MAD", symbolPosition: "prefix" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", symbolPosition: "suffix" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", symbolPosition: "prefix" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", symbolPosition: "suffix" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", symbolPosition: "prefix" },
  { code: "MNT", name: "Mongolia Tugrik", symbol: "₮", symbolPosition: "prefix" },
  { code: "MOP", name: "Macau Pataca", symbol: "P", symbolPosition: "prefix" },
  { code: "MRO", name: "Mauritania Ouguiya", symbol: "UM", symbolPosition: "suffix" },
  { code: "MRU", name: "Mauritania Ouguiya", symbol: "UM", symbolPosition: "suffix" },
  { code: "MTL", name: "Maltese Lira", symbol: "£", symbolPosition: "prefix" },
  { code: "MUR", name: "Mauritius Rupee", symbol: "Rs", symbolPosition: "prefix" },
  { code: "MVR", name: "Maldives Rufiyaa", symbol: "Rf", symbolPosition: "suffix" },
  { code: "MWK", name: "Malawi Kwacha", symbol: "MK", symbolPosition: "prefix" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", symbolPosition: "prefix" },
  { code: "MZN", name: "Mozambique Metical", symbol: "MT", symbolPosition: "suffix" },
  { code: "NAD", name: "Namibia Dollar", symbol: "N$", symbolPosition: "prefix" },
  { code: "NGN", name: "Nigeria Naira", symbol: "₦", symbolPosition: "prefix" },
  { code: "NIO", name: "Nicarag Cordoba Oro", symbol: "C$", symbolPosition: "prefix" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", symbolPosition: "suffix" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "Rs", symbolPosition: "prefix" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", symbolPosition: "prefix" },
  { code: "OMR", name: "Oman Rial", symbol: "﷼", symbolPosition: "prefix" },
  { code: "PAB", name: "Panama Balboa", symbol: "B/.", symbolPosition: "prefix" },
  { code: "PEN", name: "Peru Nuevo Sol", symbol: "S/.", symbolPosition: "prefix" },
  { code: "PGK", name: "Papua Ng Kina", symbol: "K", symbolPosition: "prefix" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", symbolPosition: "prefix" },
  { code: "PKR", name: "Pakistan Rupee", symbol: "Rs", symbolPosition: "prefix" },
  { code: "PLN", name: "Polish New Zloty", symbol: "zł", symbolPosition: "suffix" },
  { code: "PYG", name: "Paraguay Guarani", symbol: "₲", symbolPosition: "prefix" },
  { code: "QAR", name: "Qatar Rial", symbol: "﷼", symbolPosition: "prefix" },
  { code: "RON", name: "Romanian Lei", symbol: "lei", symbolPosition: "suffix" },
  { code: "RSD", name: "Serbia Dinar", symbol: "din", symbolPosition: "suffix" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", symbolPosition: "suffix" },
  { code: "RWF", name: "Rwanda Franc", symbol: "Fr", symbolPosition: "prefix" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", symbolPosition: "prefix" },
  { code: "SBD", name: "Solomon Is. Dollar", symbol: "SI$", symbolPosition: "prefix" },
  { code: "SCR", name: "Seychelles Rupee", symbol: "Rs", symbolPosition: "prefix" },
  { code: "SDG", name: "Sudanese Pound", symbol: "£", symbolPosition: "prefix" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", symbolPosition: "prefix" },
  { code: "SHP", name: "St. Helena Pound", symbol: "£", symbolPosition: "prefix" },
  { code: "SIT", name: "Slovenian Tolar", symbol: "SIT", symbolPosition: "suffix" },
  { code: "SKK", name: "Slovak Koruna", symbol: "Sk", symbolPosition: "suffix" },
  { code: "SLE", name: "Sierra Leone Leone", symbol: "Le", symbolPosition: "prefix" },
  { code: "SLL", name: "Sierra L Leone", symbol: "Le", symbolPosition: "prefix" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", symbolPosition: "prefix" },
  { code: "SRD", name: "Surinam Dollar", symbol: "$", symbolPosition: "prefix" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£", symbolPosition: "prefix" },
  { code: "STD", name: "Sao Tome Dobra", symbol: "Db", symbolPosition: "prefix" },
  { code: "STN", name: "Sao Tome Dobra", symbol: "Db", symbolPosition: "prefix" },
  { code: "SVC", name: "El Salvador Colon", symbol: "₡", symbolPosition: "prefix" },
  { code: "SYP", name: "Syrian Pound", symbol: "£", symbolPosition: "prefix" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "L", symbolPosition: "prefix" },
  { code: "THB", name: "Thai Baht", symbol: "฿", symbolPosition: "prefix" },
  { code: "TJS", name: "Tajikistan Somoni", symbol: "SM", symbolPosition: "suffix" },
  { code: "TMT", name: "Turkmenistan Manat", symbol: "T", symbolPosition: "suffix" },
  { code: "TND", name: "Tunisian Dinar", symbol: "DT", symbolPosition: "prefix" },
  { code: "TOP", name: "Tonga Paanga", symbol: "T$", symbolPosition: "prefix" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", symbolPosition: "prefix" },
  { code: "TTD", name: "TrinidadTobago Dol.", symbol: "TT$", symbolPosition: "prefix" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", symbolPosition: "prefix" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", symbolPosition: "prefix" },
  { code: "UAH", name: "Ukranian Hryvnia", symbol: "₴", symbolPosition: "prefix" },
  { code: "UGX", name: "Uganda Shilling", symbol: "USh", symbolPosition: "prefix" },
  { code: "UYU", name: "Uruguayo Peso", symbol: "$U", symbolPosition: "prefix" },
  { code: "UZS", name: "Uzbekistan Sum", symbol: "лв", symbolPosition: "suffix" },
  { code: "VEF", name: "Venez Bolivar Fuerte", symbol: "Bs.F", symbolPosition: "prefix" },
  { code: "VES", name: "Bolivar Soberano", symbol: "Bs.S", symbolPosition: "prefix" },
  { code: "VND", name: "Viet Nam Dong", symbol: "₫", symbolPosition: "suffix" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", symbolPosition: "suffix" },
  { code: "WST", name: "Samoa Tala", symbol: "WS$", symbolPosition: "prefix" },
  { code: "XAF", name: "Cfa Franc Beac", symbol: "Fr", symbolPosition: "prefix" },
  { code: "XCD", name: "E. Caribbean Dollar", symbol: "EC$", symbolPosition: "prefix" },
  { code: "XCG", name: "Caribbean Guilder", symbol: "ƒ", symbolPosition: "prefix" },
  { code: "XOF", name: "Cfa Franc Bceao", symbol: "Fr", symbolPosition: "prefix" },
  { code: "XPF", name: "Cfp Franc", symbol: "Fr", symbolPosition: "prefix" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", symbolPosition: "suffix" },
  { code: "ZAR", name: "South African Rand", symbol: "R", symbolPosition: "prefix" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", symbolPosition: "prefix" },
  { code: "ZWG", name: "Zimbabwe Gold", symbol: "ZiG", symbolPosition: "prefix" },
  { code: "ZWL", name: "Zimbabwe Dollar", symbol: "Z$", symbolPosition: "prefix" },
];

export default currencies